### ISSUE TITLE
Minting on Rinkeby always throws an exception

### ISSUE THREAD

**Issue by ezynda3** [trusttoken/true-currencies#105]
I've tried several times with differing amounts to run the faucet method for TUSD and TCAD and everytime I try the transaction fails and throws an exception. Not sure what I am doing wrong. I'm using the Etherscan dApp pages to easily invoke the methods for example TCAD https://rinkeby.etherscan.io/dapp/0x00005cad001e0900002979f7314d00fc480a29bd#writeContract

**Comment by wjmelements** [comment]
I see the same issue. Investigating.

**Comment by wjmelements** [comment]
It's a bug with their Dapp page.

**Comment by wjmelements** [comment]
It should work if you use https://rinkeby.etherscan.io/address/0x00005cad001e0900002979f7314d00fc480a29bd#writeContract

**Comment by wjmelements** [comment]
Example of working tx I sent from the Write Tab of the /address/ page: https://rinkeby.etherscan.io/tx/0x3d792e32a5258f61cbe96bfd1d12640b69af61b5ef2a8241ce40775d414fffb7

I'll escalate this to the Etherscan team.

**Comment by wjmelements** [comment]
In short, the bug is that they issue the transaction to the wrong smart contract. Instead of sending it to the proxy, they issue it to the implementation contract, which is where they pull the ABI.

Here is the transaction I sent from the TrueCAD Faucet Dapp page: https://rinkeby.etherscan.io/tx/0x2fcff12a09b6983ef5849e3a63697fc6d8073baa18d8938597744ea0edffd336
The `to` address should be 0x00005cad001e0900002979f7314d00fc480a29bd but it is 0x0f61423a7728a486516d289badcdeb2272f75f76, the implementation contract.

**Comment by wjmelements** [comment]
Thanks for reporting this to us @ezynda3

**Comment by wjmelements** [comment]
I have reported the bug to Etherscan. Closing this issue as there is a workaround.
