### ISSUE TITLE
increaseApproval vs increaseAllowance

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#120]
The specification seems nonstandard. EY prefers increaseAllowance though increaseApproval has been preferred in other locations.

**Comment by wjmelements** [comment]
We will likely patch this in the next batch of upgrades. If you have any comments on the topic please post them here before the end of December 2019.

**Comment by wjmelements** [comment]
Exactly "increaseAllowance" has 1,420 google results while exactly "increaseApproval" has 5,870 google results.

**Comment by wjmelements** [comment]
The convention of increaseAllowance seems to have begun with [this pull request](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1293), though neither the pull request nor its linked issue discuss the change.

Perhaps @frangio can offer some insight here.

**Comment by frangio** [comment]
Hi @wjmelements, can you give me some context on what is the issue here?

**Comment by wjmelements** [comment]
@frangio The community had coordinated on increaseApproval, but openzeppelin changed it to increaseAllowance in your pull request. Do you recall why? There is now inconsistency in this specification, and EY is preferring the less-common increaseAllowance.

**Comment by frangio** [comment]
We felt that it was a more consistent name with the ERC20 spec, which uses the term "allowance" rather than "approval". We also felt it was okay to make this breaking change (which we did in the 2.0 major release) because these functions are not part of the ERC20 standard. We never recommended their usage when interacting with generic ERC20 tokens, since there's no guarantee they will be available, and this change made sense from that perspective.

**Comment by wjmelements** [comment]
Okay, we will likely change to increaseAllowance and decreaseAllowance in a future update then.
