### ISSUE TITLE
All ERC20 functions broken on Legacy TrueUSD

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#297]
The original [TUSD contract](https://etherscan.io/address/0x8dd5fbce2f6a956c3022ba3663759011dd51e73e)'s ERC20 functions are all broken as of the recent upgrade.

**Comment by wjmelements** [comment]
Consequentially, over $1500 is now locked in [this contract](https://etherscan.io/address/0x4f30e682d0541eac91748bd38a648d759261b8f3).

**Comment by wjmelements** [comment]
There may be other contracts that are also broken; anything using the legacy address will fail.

**Comment by hal909** [comment]
Thanks Will! I will see if the legacy contracts are useful otherwise we
will probably stop supporting them. Can you think of anything specific that
might break or other third parties that might have stuck funds?

**Comment by wjmelements** [comment]
You've already "stopped supporting them"; you broke them without even knowing they existed. Fixing this is a matter of adding back the functions you removed.

Before you broke it, the legacy contract processed about 100 transactions per day.
Internal: https://etherscan.io/address/0x8dd5fbce2f6a956c3022ba3663759011dd51e73e/advanced#internaltx
External:
https://etherscan.io/txs?a=0x8dd5fbce2f6a956c3022ba3663759011dd51e73e
You should compensate the parties who lost gas because of your breakage, myself included.

**Comment by RafaelCosman** [comment]
@wjmelements please see this thread for a detailed explanation:

https://twitter.com/rafaelcosman/status/1306640776730869767?s=21

Based on feedback from Maker, AAVE, and other communities, we’ve decided that after 20 months of supporting the old address, the benefits of a simpler TUSD smart contract outweigh legacy support at this point.

**If you have lost gas or funds due to this deprecation, please email our team at support@trusttoken.com with the relevant amounts of ETH and TUSD (and appropriate evidence) and we’ll get you reimbursed.** 

Our apologies for any inconvenience and my bad for forgetting to announce this beforehand!

**Comment by wjmelements** [comment]
Thank you for accepting liability for your abrupt destruction of funds. I have sent the support email. If there is any delay in your compensation payments we expect 2% interest, which is in line with current DeFi rates on ETH.

**Comment by wjmelements** [comment]
We have received timely compensation. Thank you.
